import { notFound } from "next/navigation";
import { PairCompareClient } from "@/components/PairCompareClient";
import {
  apps,
  comparisons,
  getAppById,
  getComparisonById,
} from "@/lib/data";
import {
  buildAutoComparison,
  parsePairSlug,
  suggestRelatedComparisons,
} from "@/lib/build-comparison";

const knownIds = new Set(apps.map((a) => a.id));

export function generateStaticParams() {
  // Pre-built comparisons get statically generated. Other pairs render dynamically
  // (Next.js dynamicParams default = true) so any /compare/[a]-vs-[b] still works.
  return comparisons.map((c) => ({ slug: c.id }));
}

export function generateMetadata({ params }: { params: { slug: string } }) {
  const expert = getComparisonById(params.slug);
  if (expert) {
    return {
      title: `${expert.title} (2026): Which is Better? — AI App Catalog`,
      description: expert.subtitle,
    };
  }
  const parsed = parsePairSlug(params.slug, knownIds);
  if (!parsed) return { title: "Comparison not found" };
  const a1 = getAppById(parsed.app1Id);
  const a2 = getAppById(parsed.app2Id);
  if (!a1 || !a2) return { title: "Comparison not found" };
  return {
    title: `${a1.name} vs ${a2.name} (2026): Which is Better? — AI App Catalog`,
    description: `Honest, side-by-side comparison of ${a1.name} and ${a2.name} — pricing, output quality, integrations, and verdict.`,
  };
}

export default function PairComparePage({ params }: { params: { slug: string } }) {
  const expert = getComparisonById(params.slug);

  if (expert) {
    const a1 = getAppById(expert.app1);
    const a2 = getAppById(expert.app2);
    if (!a1 || !a2) notFound();
    const related = suggestRelatedComparisons(a1, a2, apps);
    return (
      <PairCompareClient
        comparison={expert}
        app1={a1}
        app2={a2}
        apps={apps}
        allComparisons={comparisons}
        related={related}
        isAutoGenerated={false}
      />
    );
  }

  const parsed = parsePairSlug(params.slug, knownIds);
  if (!parsed) notFound();
  const a1 = getAppById(parsed.app1Id);
  const a2 = getAppById(parsed.app2Id);
  if (!a1 || !a2) notFound();

  const auto = buildAutoComparison(a1, a2);
  const related = suggestRelatedComparisons(a1, a2, apps);

  return (
    <PairCompareClient
      comparison={auto}
      app1={a1}
      app2={a2}
      apps={apps}
      allComparisons={comparisons}
      related={related}
      isAutoGenerated
    />
  );
}
