import { notFound } from "next/navigation";
import { PairCompareClient } from "@/components/PairCompareClient";
import {
  getAppById,
  getApps,
  getComparisonById,
  getComparisons,
} from "@/lib/db";
import {
  buildAutoComparison,
  parsePairSlug,
  suggestRelatedComparisons,
} from "@/lib/build-comparison";

export const revalidate = 60;

export async function generateStaticParams() {
  // Pre-built comparisons get statically generated. Other pairs render dynamically
  // (Next.js dynamicParams default = true) so any /compare/[a]-vs-[b] still works.
  const comparisons = await getComparisons();
  return comparisons.map((c) => ({ slug: c.id }));
}

export async function generateMetadata({ params }: { params: { slug: string } }) {
  const expert = await getComparisonById(params.slug);
  if (expert) {
    return {
      title: `${expert.title} (2026): Which is Better? — AI App Catalog`,
      description: expert.subtitle,
    };
  }
  const apps = await getApps();
  const knownIds = new Set(apps.map((a) => a.id));
  const parsed = parsePairSlug(params.slug, knownIds);
  if (!parsed) return { title: "Comparison not found" };
  const a1 = apps.find((a) => a.id === parsed.app1Id);
  const a2 = apps.find((a) => a.id === parsed.app2Id);
  if (!a1 || !a2) return { title: "Comparison not found" };
  return {
    title: `${a1.name} vs ${a2.name} (2026): Which is Better? — AI App Catalog`,
    description: `Honest, side-by-side comparison of ${a1.name} and ${a2.name} — pricing, output quality, integrations, and verdict.`,
  };
}

export default async function PairComparePage({
  params,
}: {
  params: { slug: string };
}) {
  const [apps, allComparisons] = await Promise.all([
    getApps(),
    getComparisons(),
  ]);

  const expert = allComparisons.find((c) => c.id === params.slug) ?? null;

  if (expert) {
    const a1 = await getAppById(expert.app1);
    const a2 = await getAppById(expert.app2);
    if (!a1 || !a2) notFound();
    const related = suggestRelatedComparisons(a1, a2, apps);
    return (
      <PairCompareClient
        comparison={expert}
        app1={a1}
        app2={a2}
        apps={apps}
        allComparisons={allComparisons}
        related={related}
        isAutoGenerated={false}
      />
    );
  }

  const knownIds = new Set(apps.map((a) => a.id));
  const parsed = parsePairSlug(params.slug, knownIds);
  if (!parsed) notFound();
  const a1 = await getAppById(parsed.app1Id);
  const a2 = await getAppById(parsed.app2Id);
  if (!a1 || !a2) notFound();

  const auto = buildAutoComparison(a1, a2);
  const related = suggestRelatedComparisons(a1, a2, apps);

  return (
    <PairCompareClient
      comparison={auto}
      app1={a1}
      app2={a2}
      apps={apps}
      allComparisons={allComparisons}
      related={related}
      isAutoGenerated
    />
  );
}
