"use client";

import { useState } from "react";
import Link from "next/link";
import clsx from "clsx";
import {
  CATEGORY_META,
  PRICING_COLORS,
  type AIApp,
  type Comparison,
  type ComparisonDimension,
} from "@/lib/types";
import { ProsConsBlock } from "./ProsConsBlock";
import { AppLogo } from "./AppLogo";

interface Props {
  comparison: Comparison;
  app1: AIApp;
  app2: AIApp;
  apps: AIApp[];
  allComparisons: Comparison[];
  related?: Array<{ id: string; title: string }>;
  isAutoGenerated?: boolean;
}

export function PairCompareClient({
  comparison,
  app1,
  app2,
  apps,
  allComparisons,
  related = [],
  isAutoGenerated = false,
}: Props) {
  const [activeAppId, setActiveAppId] = useState<string>(app1.id);

  const wins = (winner: string, appId: string) => winner === appId;
  const total1 = comparison.dimensions.reduce((s, d) => s + d.app1Score, 0);
  const total2 = comparison.dimensions.reduce((s, d) => s + d.app2Score, 0);
  const overallWinner =
    total1 > total2 ? app1 : total2 > total1 ? app2 : null;

  return (
    <div className="mx-auto max-w-5xl px-4 pb-28 pt-6 sm:px-6 sm:pb-16 sm:pt-10 lg:px-8">
      <Link
        href="/compare"
        className="press inline-flex min-h-[36px] items-center gap-1 text-xs text-muted hover:text-white"
      >
        ← All comparisons
      </Link>

      {/* Header */}
      <header className="mt-4">
        <div className="mb-2 flex flex-wrap items-center gap-2">
          {isAutoGenerated ? (
            <span
              title="Built automatically from app data — pricing, ratings, tags, and pros/cons"
              className="inline-flex items-center gap-1 rounded-full border border-cyan-400/40 bg-cyan-500/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-cyan-200"
            >
              <span aria-hidden>🤖</span>
              Auto-generated from app data
            </span>
          ) : (
            <span
              title="Hand-written comparison reviewed by our team"
              className="inline-flex items-center gap-1 rounded-full border border-violet-400/40 bg-violet-500/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-violet-200"
            >
              <span aria-hidden>✍️</span>
              Expert reviewed
            </span>
          )}
        </div>
        <h1 className="text-2xl font-bold tracking-tight text-white sm:text-4xl">
          {comparison.title} (2026):{" "}
          <span className="text-muted-strong">Which is better?</span>
        </h1>
        <p className="mt-2 text-sm text-muted-strong sm:text-base">
          {comparison.subtitle}
        </p>
        <p className="mt-1 text-[11px] text-muted">
          Last updated {comparison.updatedDate}
        </p>

        {/* App tiles + VS */}
        <div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-stretch gap-3 sm:gap-5">
          <AppTile app={app1} side="left" />
          <div className="grid place-items-center px-2 text-2xl font-extrabold tracking-tight text-muted sm:text-4xl">
            VS
          </div>
          <AppTile app={app2} side="right" />
        </div>
      </header>

      {/* Verdict banner */}
      <section className="mt-6 rounded-2xl border border-violet-400/40 bg-gradient-to-r from-violet-500/15 via-bg-card to-blue-500/10 p-4 sm:p-5">
        <p className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider text-violet-200">
          <span aria-hidden>🏆</span> Overall verdict
          {overallWinner && (
            <span
              className="ml-2 rounded-full bg-violet-500/30 px-2 py-0.5 text-[10px] font-bold text-white"
            >
              Winner: {overallWinner.name}
            </span>
          )}
        </p>
        <p className="mt-2 text-sm leading-relaxed text-white sm:text-base">
          {comparison.verdict}
        </p>
      </section>

      {/* Quick picks */}
      <section className="mt-4 grid grid-cols-1 gap-3 md:grid-cols-2">
        {comparison.quickPicks.map((qp) => {
          const app = qp.app === app1.id ? app1 : app2;
          const meta = CATEGORY_META[app.category];
          return (
            <div
              key={qp.app}
              className={clsx(
                "rounded-xl border p-4",
                meta.badge.split(" ").find((c) => c.startsWith("border-")) ?? "border-border",
                "border-2",
              )}
              style={{ borderColor: `${meta.hex}55` }}
            >
              <p className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider text-emerald-200">
                <span aria-hidden>✅</span>
                {qp.label}
              </p>
              <ul className="mt-2 space-y-1.5">
                {qp.points.map((p, i) => (
                  <li key={i} className="flex gap-2 text-sm text-muted-strong">
                    <span aria-hidden className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-400" />
                    <span>{p}</span>
                  </li>
                ))}
              </ul>
              <Link
                href={`/app/${app.id}`}
                className="press mt-3 inline-flex min-h-[36px] items-center gap-1 text-xs font-medium text-accent hover:text-accent-hover"
              >
                See full {app.name} details →
              </Link>
            </div>
          );
        })}
      </section>

      {/* Dimensions */}
      <section className="mt-8">
        <h2 className="mb-3 text-base font-semibold text-white sm:text-lg">
          Score by category
        </h2>
        <ul className="space-y-3">
          {comparison.dimensions.map((d, i) => (
            <DimensionRow
              key={i}
              dimension={d}
              app1={app1}
              app2={app2}
              wins={wins}
            />
          ))}
        </ul>
        <div className="mt-3 flex justify-end gap-4 text-[11px] text-muted">
          <span>
            Total — {app1.name}: <span className="font-semibold text-muted-strong">{total1}</span>
          </span>
          <span>
            {app2.name}: <span className="font-semibold text-muted-strong">{total2}</span>
          </span>
        </div>
      </section>

      {/* Pros & cons side by side / swipeable on mobile */}
      <section className="mt-8">
        <h2 className="mb-3 text-base font-semibold text-white sm:text-lg">
          Pros &amp; cons
        </h2>

        {/* Mobile: swipeable single app at a time */}
        <div className="md:hidden">
          <div className="mb-2 flex gap-1.5 rounded-full border border-border bg-bg-card p-1 text-xs">
            {[app1, app2].map((a) => (
              <button
                key={a.id}
                type="button"
                onClick={() => setActiveAppId(a.id)}
                aria-pressed={activeAppId === a.id}
                className={clsx(
                  "press flex-1 rounded-full px-3 py-2 text-center transition",
                  activeAppId === a.id
                    ? "bg-accent/20 text-white"
                    : "text-muted hover:text-white",
                )}
              >
                {a.name}
              </button>
            ))}
          </div>
          {[app1, app2]
            .filter((a) => a.id === activeAppId)
            .map((a) => (
              <div key={a.id}>
                <ProsConsBlock pros={a.pros} cons={a.cons} compact />
              </div>
            ))}
        </div>

        {/* Desktop: side by side */}
        <div className="hidden grid-cols-2 gap-4 md:grid">
          {[app1, app2].map((a) => (
            <div key={a.id} className="rounded-xl border border-border bg-bg-card/40 p-3">
              <p className="mb-2 text-sm font-semibold text-white">{a.name}</p>
              <ProsConsBlock pros={a.pros} cons={a.cons} compact />
            </div>
          ))}
        </div>
      </section>

      {/* Best for + compatible */}
      <section className="mt-8 grid grid-cols-1 gap-3 md:grid-cols-2">
        {[app1, app2].map((a) => (
          <div key={a.id} className="rounded-xl border border-border bg-bg-card p-4">
            <p className="text-sm font-semibold text-white">{a.name}</p>
            {a.bestFor.length > 0 && (
              <div className="mt-2">
                <p className="text-[10px] uppercase tracking-wider text-muted">Best for</p>
                <div className="mt-1.5 flex flex-wrap gap-1">
                  {a.bestFor.map((b) => (
                    <span
                      key={b}
                      className={clsx(
                        "rounded-full border px-2 py-0.5 text-[11px]",
                        CATEGORY_META[a.category].badge,
                      )}
                    >
                      {b}
                    </span>
                  ))}
                </div>
              </div>
            )}
            <p className="mt-3 text-[10px] uppercase tracking-wider text-muted">Pairs with</p>
            <p className="mt-1 text-xs text-muted-strong">
              {a.compatibleWith.slice(0, 5).map((id) => apps.find((x) => x.id === id)?.name).filter(Boolean).join(" · ")}
            </p>
            <Link
              href={`/app/${a.id}`}
              className="press mt-3 inline-flex min-h-[40px] items-center justify-center rounded-md bg-accent/15 px-3 text-xs font-medium text-accent transition hover:bg-accent/25"
            >
              See full {a.name} details →
            </Link>
          </div>
        ))}
      </section>

      {/* You might also compare */}
      {related.length > 0 && (
        <section className="mt-8">
          <h2 className="mb-3 text-base font-semibold text-white sm:text-lg">
            You might also compare
          </h2>
          {/* Mobile: horizontal swipe; desktop: grid */}
          <div className="-mx-4 overflow-x-auto px-4 sm:mx-0 sm:px-0">
            <ul className="flex gap-2 pb-2 sm:grid sm:grid-cols-2 lg:grid-cols-4">
              {related.map((r) => (
                <li key={r.id} className="w-[220px] shrink-0 sm:w-auto">
                  <Link
                    href={`/compare/${r.id}`}
                    className="press flex h-full min-h-[64px] items-center justify-between rounded-xl border border-border bg-bg-card p-3 text-sm text-white transition active:bg-bg-hover hover:border-accent/40"
                  >
                    <span className="truncate font-medium">{r.title}</span>
                    <span aria-hidden className="ml-2 shrink-0 text-muted">→</span>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </section>
      )}

      {/* Compare different pair */}
      <section className="mt-8 rounded-xl border border-border bg-bg-card p-4">
        <p className="text-sm font-semibold text-white">Compare a different pair</p>
        <PairPicker
          apps={apps}
          existingComparisons={allComparisons}
          excludeId={comparison.id}
        />
      </section>
    </div>
  );
}

function AppTile({ app, side }: { app: AIApp; side: "left" | "right" }) {
  const m = CATEGORY_META[app.category];
  return (
    <Link
      href={`/app/${app.id}`}
      className={clsx(
        "press flex flex-col items-center gap-2 rounded-2xl border-2 bg-bg-card p-4 text-center transition active:scale-[0.98] hover:bg-bg-hover",
        side === "left" ? "items-start text-left sm:items-center sm:text-center" : "items-end text-right sm:items-center sm:text-center",
      )}
      style={{ borderColor: `${m.hex}55` }}
    >
      <AppLogo
        logoUrl={app.logoUrl}
        appName={app.name}
        category={app.category}
        size="lg"
        className={m.glow}
      />
      <h2 className="text-base font-bold leading-tight text-white sm:text-lg">
        {app.name}
      </h2>
      <span
        className={clsx(
          "inline-flex rounded-full border px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide",
          PRICING_COLORS[app.pricing],
        )}
      >
        {app.pricing_details.starting_price === "$0"
          ? "Free"
          : `from ${app.pricing_details.starting_price}`}
      </span>
    </Link>
  );
}

function DimensionRow({
  dimension,
  app1,
  app2,
  wins,
}: {
  dimension: ComparisonDimension;
  app1: AIApp;
  app2: AIApp;
  wins: (winner: string, appId: string) => boolean;
}) {
  const m1 = CATEGORY_META[app1.category];
  const m2 = CATEGORY_META[app2.category];
  const isTie = dimension.winner === "tie";
  return (
    <li className="rounded-xl border border-border bg-bg-card p-4">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <p className="text-sm font-semibold text-white">{dimension.name}</p>
        {isTie ? (
          <span className="rounded-full border border-border bg-bg px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-muted">
            Tie
          </span>
        ) : (
          <span
            className="rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-white"
            style={{ backgroundColor: dimension.winner === app1.id ? `${m1.hex}50` : `${m2.hex}50` }}
          >
            🏆 {dimension.winner === app1.id ? app1.name : app2.name}
          </span>
        )}
      </div>

      <div className="mt-3 grid gap-2">
        <ScoreBar
          name={app1.name}
          score={dimension.app1Score}
          color={m1.hex}
          winning={wins(dimension.winner, app1.id) || isTie}
        />
        <ScoreBar
          name={app2.name}
          score={dimension.app2Score}
          color={m2.hex}
          winning={wins(dimension.winner, app2.id) || isTie}
        />
      </div>

      <p className="mt-3 text-xs leading-relaxed text-muted-strong sm:text-sm">
        {dimension.explanation}
      </p>
    </li>
  );
}

function ScoreBar({
  name,
  score,
  color,
  winning,
}: {
  name: string;
  score: number;
  color: string;
  winning: boolean;
}) {
  const pct = Math.max(0, Math.min(5, score)) / 5 * 100;
  return (
    <div>
      <div className="mb-0.5 flex items-center justify-between text-[11px]">
        <span className={clsx("truncate", winning ? "font-semibold text-white" : "text-muted-strong")}>
          {name}
        </span>
        <span className="tabular-nums text-muted">{score}/5</span>
      </div>
      <div className="relative h-2 overflow-hidden rounded-full bg-bg">
        <div
          className="absolute inset-y-0 left-0 rounded-full transition-[width] duration-500"
          style={{ width: `${pct}%`, backgroundColor: color, opacity: winning ? 0.9 : 0.55 }}
        />
      </div>
    </div>
  );
}

function PairPicker({
  apps,
  existingComparisons,
  excludeId,
}: {
  apps: AIApp[];
  existingComparisons: Comparison[];
  excludeId: string;
}) {
  return (
    <ul className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-2">
      {existingComparisons
        .filter((c) => c.id !== excludeId)
        .slice(0, 6)
        .map((c) => {
          const a1 = apps.find((a) => a.id === c.app1);
          const a2 = apps.find((a) => a.id === c.app2);
          if (!a1 || !a2) return null;
          return (
            <li key={c.id}>
              <Link
                href={`/compare/${c.id}`}
                className="press flex min-h-[44px] items-center justify-between rounded-lg border border-border bg-bg-card/60 px-3 py-2 text-xs text-white transition active:bg-bg-hover hover:border-accent/40"
              >
                <span className="truncate">{c.title}</span>
                <span aria-hidden className="text-muted">→</span>
              </Link>
            </li>
          );
        })}
    </ul>
  );
}
