import type {
  AIApp,
  Comparison,
  ComparisonDimension,
  ComparisonQuickPick,
} from "./types";

// Add a flag for the UI to know whether this page came from JSON or was synthesized.
// We extend Comparison through a sibling type so we don't break the strict shape.
export type AutoComparison = Comparison & { isAutoGenerated: true };
export type ExpertComparison = Comparison & { isAutoGenerated?: false };
export type AnyComparison = AutoComparison | ExpertComparison;

/* -------------------- Slug parsing -------------------- */

/** Split "appA-vs-appB" into ["appA","appB"]. App ids may contain hyphens. */
export function parsePairSlug(
  slug: string,
  knownIds: Set<string>,
): { app1Id: string; app2Id: string } | null {
  const idx = slug.indexOf("-vs-");
  if (idx <= 0) return null;
  const a = slug.slice(0, idx);
  const b = slug.slice(idx + "-vs-".length);
  if (!knownIds.has(a) || !knownIds.has(b)) return null;
  if (a === b) return null;
  return { app1Id: a, app2Id: b };
}

export function pairSlug(app1Id: string, app2Id: string): string {
  return `${app1Id}-vs-${app2Id}`;
}

/* -------------------- Pricing parsing -------------------- */

function parseStartingPrice(s: string | undefined | null): number {
  if (!s) return 9999;
  const m = s.match(/\$(\d+)/);
  return m ? Number(m[1]) : 0;
}

function pickWinner(
  app1: AIApp,
  s1: number,
  app2: AIApp,
  s2: number,
): string {
  if (s1 > s2) return app1.id;
  if (s2 > s1) return app2.id;
  return "tie";
}

/* -------------------- Dimension scorers -------------------- */

function scoreEaseOfUse(a: AIApp): number {
  let s = 3;
  const tagText = a.tags.join(" ").toLowerCase();
  if (/\b(easy|no.?code|drag.?and.?drop|browser|template)\b/.test(tagText)) s += 2;
  if (/\b(api|developer|self.?host|framework)\b/.test(tagText)) s -= 1;
  if (/\b(mobile|ios|android)\b/.test(tagText)) s += 1;
  if (a.pricing_details.free_tier) s += 1;
  return clamp(s);
}

function scorePricing(a: AIApp): number {
  if (a.pricing_details.free_tier) return 5;
  const start = parseStartingPrice(a.pricing_details.starting_price);
  if (start < 10) return 4;
  if (start <= 20) return 3;
  if (start <= 50) return 2;
  return 1;
}

function scoreFreeTier(a: AIApp): number {
  if (!a.pricing_details.free_tier) return 1;
  const limits = a.pricing_details.free_tier_limits ?? "";
  if (!limits) return 3;
  if (/unlimited|free for|no limit|generous/i.test(limits)) return 5;
  // Heuristic: longer / more specific limits often imply more headroom
  if (limits.length > 30) return 4;
  return 3;
}

function scoreIntegrations(a: AIApp): number {
  let s = 3;
  const tagText = a.tags.join(" ").toLowerCase();
  if (/\b(api|sdk)\b/.test(tagText)) s += 2;
  if (a.compatibleWith.length >= 10) s += 2;
  else if (a.compatibleWith.length >= 5) s += 1;
  return clamp(s);
}

function scoreMobile(a: AIApp): number {
  const tagText = a.tags.join(" ").toLowerCase();
  if (/\b(mobile|ios|android)\b/.test(tagText)) return 5;
  return 2;
}

function scoreOutputQuality(a: AIApp): number {
  if (a.rating >= 4.5) return 5;
  if (a.rating >= 4.0) return 4;
  if (a.rating >= 3.5) return 3;
  return 2;
}

function scoreCommunity(a: AIApp): number {
  if (a.reviewCount >= 1000) return 5;
  if (a.reviewCount >= 500) return 4;
  if (a.reviewCount >= 100) return 3;
  return 2;
}

function clamp(n: number): number {
  return Math.max(1, Math.min(5, Math.round(n)));
}

/* -------------------- Dimension explanations -------------------- */

function explainOutputQuality(a1: AIApp, s1: number, a2: AIApp, s2: number): string {
  if (s1 === s2) {
    return `Both apps land in a similar quality band — average rating ${a1.rating.toFixed(1)} for ${a1.name} vs ${a2.rating.toFixed(1)} for ${a2.name}. Output is comparable in real-world use.`;
  }
  const winner = s1 > s2 ? a1 : a2;
  const loser = s1 > s2 ? a2 : a1;
  return `${winner.name} edges ahead on output quality, with an average rating of ${winner.rating.toFixed(1)} from ${winner.reviewCount.toLocaleString()} reviews vs ${loser.rating.toFixed(1)} for ${loser.name}.`;
}

function explainEaseOfUse(a1: AIApp, s1: number, a2: AIApp, s2: number): string {
  if (s1 === s2) {
    return `Both apps have a similar learning curve — neither is dramatically easier to pick up than the other.`;
  }
  const easier = s1 > s2 ? a1 : a2;
  const harder = s1 > s2 ? a2 : a1;
  const easierIsApi = /api|developer|framework/i.test(easier.tags.join(" "));
  const harderIsApi = /api|developer|framework/i.test(harder.tags.join(" "));
  if (harderIsApi && !easierIsApi) {
    return `${easier.name} is friendlier for non-technical users. ${harder.name} is more developer-oriented and rewards comfort with APIs and configuration.`;
  }
  return `${easier.name} is the easier on-ramp — less setup, fewer surprises. ${harder.name} has more depth but expects more from new users.`;
}

function explainPricing(a1: AIApp, s1: number, a2: AIApp, s2: number): string {
  const p1 = a1.pricing_details.starting_price || a1.pricing;
  const p2 = a2.pricing_details.starting_price || a2.pricing;
  if (s1 === s2) {
    return `Both apps are priced in a similar range (${p1} vs ${p2}). Pricing won't be the deciding factor here.`;
  }
  const cheaper = s1 > s2 ? a1 : a2;
  const cheaperPrice = s1 > s2 ? p1 : p2;
  const pricier = s1 > s2 ? a2 : a1;
  const pricierPrice = s1 > s2 ? p2 : p1;
  return `${cheaper.name} is more affordable at ${cheaperPrice} vs ${pricierPrice} for ${pricier.name}. If budget matters, ${cheaper.name} wins this category.`;
}

function explainFreeTier(a1: AIApp, s1: number, a2: AIApp, s2: number): string {
  const t1 = a1.pricing_details.free_tier;
  const t2 = a2.pricing_details.free_tier;
  if (t1 && !t2) {
    return `${a1.name} has a free tier (${a1.pricing_details.free_tier_limits || "limited features"}). ${a2.name} doesn't, so you commit on day one.`;
  }
  if (t2 && !t1) {
    return `${a2.name} has a free tier (${a2.pricing_details.free_tier_limits || "limited features"}). ${a1.name} doesn't, so you commit on day one.`;
  }
  if (!t1 && !t2) {
    return `Neither app has a free tier — both require a subscription from day one.`;
  }
  if (s1 === s2) {
    return `Both have free tiers with similar headroom (${a1.pricing_details.free_tier_limits || "limited"} vs ${a2.pricing_details.free_tier_limits || "limited"}).`;
  }
  const better = s1 > s2 ? a1 : a2;
  const worse = s1 > s2 ? a2 : a1;
  return `${better.name}'s free tier is more generous (${better.pricing_details.free_tier_limits}). ${worse.name}'s free tier is more of a teaser.`;
}

function explainIntegrations(a1: AIApp, s1: number, a2: AIApp, s2: number): string {
  if (s1 === s2) {
    return `Both apps have similar ecosystem reach — ${a1.compatibleWith.length} pair-with relationships for ${a1.name} and ${a2.compatibleWith.length} for ${a2.name}.`;
  }
  const winner = s1 > s2 ? a1 : a2;
  const loser = s1 > s2 ? a2 : a1;
  return `${winner.name} plugs into more of the AI stack — ${winner.compatibleWith.length} compatible apps in our catalog vs ${loser.compatibleWith.length} for ${loser.name}.`;
}

function explainMobile(a1: AIApp, s1: number, a2: AIApp, s2: number): string {
  if (s1 === s2) {
    return s1 >= 4
      ? `Both apps have polished mobile experiences.`
      : `Neither app has a strong mobile story — both are best on desktop.`;
  }
  const winner = s1 > s2 ? a1 : a2;
  const loser = s1 > s2 ? a2 : a1;
  return `${winner.name} has a real mobile app. ${loser.name} is mostly a desktop or browser experience.`;
}

function explainCommunity(a1: AIApp, s1: number, a2: AIApp, s2: number): string {
  if (s1 === s2) {
    return `Both apps have comparable community size — ${a1.reviewCount.toLocaleString()} reviews vs ${a2.reviewCount.toLocaleString()}.`;
  }
  const winner = s1 > s2 ? a1 : a2;
  const loser = s1 > s2 ? a2 : a1;
  return `${winner.name} has the bigger community (${winner.reviewCount.toLocaleString()} reviews vs ${loser.reviewCount.toLocaleString()}). More tutorials, more shared prompts, more answers when you're stuck.`;
}

/* -------------------- Quick picks -------------------- */

function buildQuickPick(app: AIApp): ComparisonQuickPick {
  const points: string[] = [];
  // Pull from bestFor (first 2)
  for (const b of app.bestFor.slice(0, 2)) {
    points.push(`You're focused on ${b}`);
  }
  // First pro (often the strongest)
  if (app.pros[0]) points.push(app.pros[0]);
  // A differentiating tag if we still need one
  if (points.length < 3) {
    const interesting = app.tags.find((t) =>
      /open source|api|free|mobile|browser|enterprise/i.test(t),
    );
    if (interesting) points.push(`You want ${interesting} support out of the box`);
  }
  if (points.length < 3 && app.verdict) points.push(app.verdict);
  return {
    app: app.id,
    label: `Choose ${app.name} if…`,
    points: points.slice(0, 4),
  };
}

/* -------------------- Overall verdict -------------------- */

function buildVerdict(a1: AIApp, total1: number, a2: AIApp, total2: number): string {
  if (a1.category === a2.category) {
    if (Math.abs(total1 - total2) <= 2) {
      return `It's genuinely close. ${a1.name} wins if you prioritize ${a1.bestFor[0] ?? a1.category.toLowerCase()}; ${a2.name} is the better pick if ${a2.bestFor[0] ?? a2.category.toLowerCase()} matters more to you.`;
    }
    const winner = total1 > total2 ? a1 : a2;
    const loser = total1 > total2 ? a2 : a1;
    return `${winner.name} edges ahead for most users thanks to ${winner.pros[0] ? winner.pros[0].toLowerCase() : "stronger overall ratings"}. That said, ${loser.name} is worth considering if ${loser.pros[0] ? loser.pros[0].toLowerCase() : "its specific strengths"} matters more to you.`;
  }
  return `${a1.name} and ${a2.name} solve different problems — ${a1.name} focuses on ${a1.category.toLowerCase()} while ${a2.name} handles ${a2.category.toLowerCase()}. Most users end up with both rather than choosing between them.`;
}

/* -------------------- Build full comparison -------------------- */

interface Scorer {
  name: string;
  fn: (a: AIApp) => number;
  explain: (a1: AIApp, s1: number, a2: AIApp, s2: number) => string;
}

const SCORERS: Scorer[] = [
  { name: "Output Quality", fn: scoreOutputQuality, explain: explainOutputQuality },
  { name: "Ease of Use", fn: scoreEaseOfUse, explain: explainEaseOfUse },
  { name: "Pricing / Value", fn: scorePricing, explain: explainPricing },
  { name: "Free Tier", fn: scoreFreeTier, explain: explainFreeTier },
  { name: "Integrations", fn: scoreIntegrations, explain: explainIntegrations },
  { name: "Mobile Experience", fn: scoreMobile, explain: explainMobile },
  { name: "Community & Support", fn: scoreCommunity, explain: explainCommunity },
];

export function buildAutoComparison(app1: AIApp, app2: AIApp): AutoComparison {
  const dimensions: ComparisonDimension[] = SCORERS.map((sc) => {
    const s1 = sc.fn(app1);
    const s2 = sc.fn(app2);
    return {
      name: sc.name,
      app1Score: s1,
      app2Score: s2,
      winner: pickWinner(app1, s1, app2, s2),
      explanation: sc.explain(app1, s1, app2, s2),
    };
  });

  const total1 = dimensions.reduce((s, d) => s + d.app1Score, 0);
  const total2 = dimensions.reduce((s, d) => s + d.app2Score, 0);

  const subtitle =
    app1.category === app2.category
      ? `Two ${app1.category.toLowerCase()} tools, head to head`
      : `${app1.category} meets ${app2.category}`;

  return {
    id: pairSlug(app1.id, app2.id),
    app1: app1.id,
    app2: app2.id,
    title: `${app1.name} vs ${app2.name}`,
    subtitle,
    verdict: buildVerdict(app1, total1, app2, total2),
    updatedDate: new Date().toISOString().slice(0, 10),
    dimensions,
    quickPicks: [buildQuickPick(app1), buildQuickPick(app2)],
    isAutoGenerated: true,
  };
}

/* -------------------- Suggestion helpers -------------------- */

/** Suggest comparison pairs for a given app: same-category competitors + compatible apps. */
export function suggestComparisonsForApp(
  app: AIApp,
  apps: AIApp[],
  opts: { sameCategory?: number; compatible?: number } = {},
): Array<{ id: string; title: string; otherApp: AIApp }> {
  const { sameCategory = 3, compatible = 2 } = opts;
  const seen = new Set<string>([app.id]);
  const picks: AIApp[] = [];

  // Top same-category by review count, excluding self
  const sameCat = apps
    .filter((a) => a.category === app.category && a.id !== app.id)
    .sort((a, b) => b.reviewCount - a.reviewCount)
    .slice(0, sameCategory);
  for (const c of sameCat) {
    if (!seen.has(c.id)) {
      picks.push(c);
      seen.add(c.id);
    }
  }

  // Compatible apps from a different category
  const comp = app.compatibleWith
    .map((id) => apps.find((a) => a.id === id))
    .filter((a): a is AIApp => a !== undefined && a.category !== app.category)
    .sort((a, b) => b.reviewCount - a.reviewCount)
    .slice(0, compatible);
  for (const c of comp) {
    if (!seen.has(c.id)) {
      picks.push(c);
      seen.add(c.id);
    }
  }

  return picks.map((other) => ({
    id: pairSlug(app.id, other.id),
    title: `${app.name} vs ${other.name}`,
    otherApp: other,
  }));
}

/** Suggest comparisons related to a pair (used at the bottom of /compare/[slug]). */
export function suggestRelatedComparisons(
  app1: AIApp,
  app2: AIApp,
  apps: AIApp[],
  limit = 4,
): Array<{ id: string; title: string }> {
  const seen = new Set<string>();
  seen.add(pairSlug(app1.id, app2.id));
  seen.add(pairSlug(app2.id, app1.id));

  const out: Array<{ id: string; title: string }> = [];
  const push = (a: AIApp, b: AIApp) => {
    const id = pairSlug(a.id, b.id);
    if (seen.has(id) || seen.has(pairSlug(b.id, a.id))) return;
    if (out.length >= limit) return;
    seen.add(id);
    out.push({ id, title: `${a.name} vs ${b.name}` });
  };

  // Same category as app1
  const sameCatA = apps
    .filter((a) => a.category === app1.category && a.id !== app1.id && a.id !== app2.id)
    .sort((a, b) => b.reviewCount - a.reviewCount);
  for (const c of sameCatA) push(app1, c);

  // Same category as app2
  const sameCatB = apps
    .filter((a) => a.category === app2.category && a.id !== app1.id && a.id !== app2.id)
    .sort((a, b) => b.reviewCount - a.reviewCount);
  for (const c of sameCatB) push(app2, c);

  // Compatible with app1 (different category)
  for (const id of app1.compatibleWith) {
    const c = apps.find((a) => a.id === id);
    if (c && c.id !== app2.id) push(app1, c);
  }

  return out.slice(0, limit);
}
